### ISSUE TITLE
Dashboard fails to load when using an external identity provider

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#1002]
If you bootstrap using an external identity provider the dashboard does not load.

dashboard version 0.6.2

![Screen Shot 2021-05-18 at 9.47.20 PM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/c54c8b4e-f6e3-498c-b209-c62592608d39)

https://discourse.charmhub.io/t/using-an-external-identity-provider-with-juju-controllers/206

**Comment by hatched** [comment]
This will be fixed with the next release of jujulib 

The error is now surfaced instead of blowing up the app.

![Screen Shot 2021-05-18 at 9.59.01 PM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/fafc67e8-0f84-4401-9e10-fa6ce9891f0b)

**Comment by hatched** [comment]
At this point there really isn't any way for the user to remedy the situation. They can clear the localstorage and request new macaroons but failing that the fix needs to be done upstream. 

Thoughts on expanding this messaging to include a note to this effect?

**Comment by anthonydillon** [comment]
This might be a good place for a situational docs link to further explain the situation and allow the users to comment.

**Comment by hatched** [comment]
Completed in beta6 on npm.
