### ISSUE TITLE
Juju Dashboard not installed  

### ISSUE THREAD

**Issue by moula** [canonical-web-and-design/jaas-dashboard#1022]
Hi, 
Juju 2.9.4 
When i try to create juju-controller with : juju bootstrap... 
I have the error message : 
Unable to fetch Juju Dashboard info: error fetching simplestreams metadata: "content-download" data not found
Thank's 
Moula. 
![Capture d’écran du 2021-06-01 21-40-57](https://user-images.githubusercontent.com/1804815/120381439-b5b87080-c322-11eb-803e-1b577a776569.png)

**Comment by moula** [comment]
![Capture d’écran du 2021-06-01 21-48-13](https://user-images.githubusercontent.com/1804815/120381814-38413000-c323-11eb-8335-af69546afe1a.png)

**Comment by hatched** [comment]
Thanks for bring this up @moula it's known and we're currently working on a resolution. I'll update this issue when it's been resolved.

**Comment by hatched** [comment]
This has now been resolved. New bootstraps will now install the dashboard v0.7.1. If you have any existing controllers you can fix them by running `juju upgrade-dashboard` and it'll pull it down and install it.
