### ISSUE TITLE
The link of  juju web cli " documentation " does not work

### ISSUE THREAD

**Issue by moula** [canonical-web-and-design/jaas-dashboard#1028]
Welcome to the Juju Web CLI - see the full documentation here.
maybe it's just in development.
![Capture d’écran du 2021-06-05 16-51-26](https://user-images.githubusercontent.com/1804815/120895775-d03e6280-c61e-11eb-8f98-0c1b6a1a92f0.png)

![Capture d’écran du 2021-06-05 16-51-52](https://user-images.githubusercontent.com/1804815/120895781-d7fe0700-c61e-11eb-81bb-5f38595a8607.png)

**Comment by hatched** [comment]
It looks like some of the paths were inadvertently changed in the Juju documentation.

The root path is https://discourse.charmhub.io/t/using-the-juju-web-cli/3723 and we'll work on getting the dashboard documentation fixed up.

**Comment by hatched** [comment]
A redirect has been put in place for the path on the previously released dashboards.

https://juju.is/docs/webcli > https://juju.is/docs/olm/using-the-juju-web-cli
