### ISSUE TITLE
Allow to share models from the models overview pane

### ISSUE THREAD

**Issue by erik78se** [canonical-web-and-design/jaas-dashboard#1034]
I would perhaps consider allowing to share a model from the "models" pane, so I wouldn't need to browse into the model to share it. Its makes more sense to me at least.

GUI: v0.7.1

![image](https://user-images.githubusercontent.com/850603/121096339-4e069780-c7f2-11eb-977d-ea317280f78a.png)

**Comment by clagom** [comment]
Thank you for your suggestion Erik. Indeed we have worked on designs with this and other actions that can be triggered from the rows directly; "share" from the list of models makes sense.

**Comment by erik78se** [comment]
Sounds good, this looks very promising. I'll try use the GUI more to find bugs and suggestions.
