### ISSUE TITLE
Controller connection disconnects before subsequent modelInfo calls can be made

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#105]
**Describe the bug**
The controller connection appears to disconnect after a short period of time. If you leave the application running you'll eventually see it time out. It's possible we have to enable the pinger to keep the connection alive. With a sufficiently large list of models the model status requests take too long and the next controller request falls outside the 'keep alive' time limit.

**To Reproduce**
1. Open application and have it list the models
2. Open the devtools and wait
3. The controller connection will time out.

**Screenshots**
<img width="1411" alt="Screen Shot 2019-10-23 at 12 22 37 PM" src="https://user-images.githubusercontent.com/532033/67422494-d558b600-f58f-11e9-8793-22282e4de8e3.png">

**Comment by cristinadresch** [comment]
@hatched we dont need to do this for the demo in vancouver right?

**Comment by hatched** [comment]
@cristinadresch well it's finished now, but yes without it the connection would time out during the demo.

**Comment by cristinadresch** [comment]
Ahh I see, good that you managed to do it then! Thanks for the update @hatched
