### ISSUE TITLE
[share model] visual confirmation after adding a person

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#1053]
Can we add a visual confirmation (blinking? colour for a while? @long-chung I think you designed it?) or a toast/notification?
![Screenshot 2021-06-16 at 09.20.09.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/ac88c34b-4603-43ab-9c29-8a5fc27314b2)

**Comment by long-chung** [comment]
New user should animate in when submitted; yes, we could add a notification to make it more obvious.

Here's the link to the current interaction for reference:
https://drive.google.com/file/d/1jgz7hJ24xyBcxadhaLSupqxZvhclDDbK/view?usp=sharing

**Comment by barrymcgee** [comment]
A confirmation toast notification when adding a new user has already been completed and I've just now deployed to jaas.ai
