### ISSUE TITLE
Juju gui: something went wrong

### ISSUE THREAD

**Issue by bsamadi** [canonical-web-and-design/jaas-dashboard#1101]
**Describe the bug**
I ran `juju gui` and I received an error message: something went wrong.

**To Reproduce**
1. Run `juju gui`
2. Open the link: `https://localhost:38583/dashboard`
3. Log in with the provided information
4. See error: Error: Something has gone wrong. If this issue persists, please raise an issue on GitHub.

**Expected behavior**
It is my first time running the gui. I'd expect to see a functional web application.

**Screenshots**
Login page:
![](https://i.imgur.com/G0qj656.png)

Next page:
![](https://i.imgur.com/f6ylPGy.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 90.0

**Additional context**
I have deployed Kubeflow with Juju but I have no idea how I can open the Kubeflow dashboard. I was hoping that juju gui would help me. 

Here is the error message in the console: [instrument.ts 129:35](https://gist.github.com/bsamadi/511b86dbcd51d069b3908948ea9a939e)

This is what I get on Brave:

![](https://i.imgur.com/FAxrT40.png)

**Comment by hatched** [comment]
Thanks for reporting this issue. This issue has been fixed locally but hasn't yet been rolled out, will try and get that done soon.

The Juju dashboard won't however help you with the kubeflow dashboard. In the meantime here is a link to the kubeflow dashboard charm which has links to its documentation. https://charmhub.io/kubeflow-dashboard

**Comment by hatched** [comment]
@bsamadi I've updated the dashboard to 0.8.1 which should resolve the issue you've mentioned. You can upgrade the dashboard on your controller by running `juju upgrade-dashboard`. Afterwards refresh and ensure that you see `0.8.1` in the left sidebar. 

If this doesn't resolve your issue feel free to re-open.
