### ISSUE TITLE
AuthFailure: AWS was not able to validate the provided access credentials for old model

### ISSUE THREAD

**Issue by eliskovets** [canonical-web-and-design/jaas-dashboard#1130]
I'm getting "AuthFailure: AWS was not able to validate the provided access credentials" when trying to do something with the old model, even if credentials for the controller is in "valid" state: 
```
credential:
    name: default
    owner: xxxx@external
    cloud: aws
    validity-check: valid
```
Debug mode doesn't help me much:
```
13:14:50 INFO  juju.cmd.juju.machine add.go:316 model provisioning
failed to create 2 machines
13:14:50 DEBUG juju.api monitor.go:35 RPC connection died
13:14:50 DEBUG juju.api monitor.go:35 RPC connection died
13:14:50 DEBUG juju.api monitor.go:35 RPC connection died
```
Could you please tell me what can cause the issue?
Thank you. 

PS. Same credentials works for another freshly created model.

**Comment by hatched** [comment]
Hi @eliskovets this is the repository for the dashboard itself, it seems like you're running into an issue with Juju/JAAS.

You'll probably be able to get some help with this issue over on the forum: https://discourse.charmhub.io/
