### ISSUE TITLE
Run Action crash for Nextcloud charm

### ISSUE THREAD

**Issue by erik78se** [canonical-web-and-design/jaas-dashboard#1164]
**Describe the bug**
When trying to use "Run Action" from nextcloud (Using 0.8.1 dashboard)

https://charmhub.io/nextcloud  (edge 611d74d)

**To Reproduce**
1. Go to 'Application' for nextcloud charm'
2. Click on 'Run Action'

**Expected behavior**
The right hand pane opens with actions available.

**Screenshots**
![image](https://user-images.githubusercontent.com/850603/138182569-ee6bd9a0-492d-4b95-9743-918272d9b9a9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome 
 - Version Version 94.0.4606.71 (Official Build) (64-bit)

**Comment by hatched** [comment]
Thanks, we'll take a look!

**Comment by hatched** [comment]
Issue is caused by the option `domain` for the action `set-trusted-domain` does not contain a description. Descriptions are not required so will guard against this.

**Comment by erik78se** [comment]
How can I get a fix going here?

Den ons 8 dec. 2021 03:01Jeff Pihach ***@***.***> skrev:

**Comment by hatched** [comment]
@erik78se You can find the release with this fix here: https://github.com/canonical-web-and-design/jaas-dashboard/releases/tag/0.9.1
