### ISSUE TITLE
Remove the animation on the button with chevron

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#117]
Remove the animation on the button with chevron, it will then match this vanilla update:

https://vanilla-framework-canonical-web-and-design-pr-2611.run.demo.haus/examples/patterns/contextual-menu/contextual-menu-indicator/

**Comment by barrymcgee** [comment]
This is a default browser accessibility feature. We shouldn't remove it without providing an alternative. See: https://a11yproject.com/posts/never-remove-css-outlines/
