### ISSUE TITLE
models crash in GUI on JAAS

### ISSUE THREAD

**Issue by EMCP** [canonical-web-and-design/jaas-dashboard#1189]
**Describe the bug**
in JAAS i clicked on my model and was greeted with a dialog to report a bug here

**To Reproduce**
1. Go to '[...](https://jaas.ai/)'
2. Click on 'your models'
3. I have only 1 model in AWS.. called `my-first-mahrio-dev` , I click on it in Firefox

![image](https://user-images.githubusercontent.com/3691722/144124357-f102d489-75f5-41e6-a6ff-09d5f5cb2b62.png)

![image](https://user-images.githubusercontent.com/3691722/144124399-9d3952fa-3d86-4443-8046-92ccaf59edcb.png)

**Expected behavior**
Shouldn't see error and instead see my model

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser FireFox
 - Version 94.0

**Comment by hatched** [comment]
Thanks for this bug report, this is a known bug and we're working on getting it resolved.
