### ISSUE TITLE
Listing page: Spacing between icons is too large

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#119]
<img width="174" alt="Screen Shot 2019-10-30 at 10 00 03 AM" src="https://user-images.githubusercontent.com/532033/67889219-0a2ab700-fb14-11e9-843c-97886e1f8c9c.png">

vs 

<img width="140" alt="Screen Shot 2019-10-30 at 12 52 00 PM" src="https://user-images.githubusercontent.com/532033/67889242-14e54c00-fb14-11e9-9e64-14aaedb03b24.png">

Introduced https://github.com/canonical-web-and-design/jaas-dashboard/pull/111

**Comment by clagom** [comment]
Also please swap machine with units as per design. Spencer might see the sizes of the icons, look smaller

**Comment by spencerbygraves** [comment]
@hatched @barrymcgee The icons should be 16x16 please:

![image](https://user-images.githubusercontent.com/9105999/68014642-0d46b400-fc88-11e9-8202-3d159492b603.png)

Thanks.
