### ISSUE TITLE
Upgrade from 0.8.1 to 0.9.1 from file isn't working

### ISSUE THREAD

**Issue by erik78se** [canonical-web-and-design/jaas-dashboard#1196]
I upgraded a controller juju-dashboard from 0.8.1 -> 0.9.1

    $ juju upgrade-dashboard ./juju-dashboard-0.9.1.tar.bz2
    Juju Dashboard switched to version 0.9.1
 

But the juju dashboard is just blank white. No error message. White page. Nothing.

Switching back, with 

    juju upgade-dashboard

makes 0.8.1 come back and it works again.

The release doesn't work?

controller-model-version: 2.9.18
client version: 2.9.21-ubuntu-amd64

**Comment by hatched** [comment]
Thanks for filing this issue, I'll investigate. While I do that would you be able to clear your browser cache after doing the update (or try another browser) just to rule that out.

**Comment by erik78se** [comment]
I opened up a new "private window" in firefox and tried again. No effect. Same blank page,

**Comment by hatched** [comment]
Thanks, I'm digging into it now.

**Comment by hatched** [comment]
@erik78se You should be good to go with [0.9.2](https://github.com/canonical-web-and-design/jaas-dashboard/releases/tag/0.9.2) now, sorry about that.

The `upgrade-dashboard` command is pulling from streams which I haven't yet updated (which is why it gets you 0.8.1). If this release works well for you then I'll push this up to streams.

**Comment by erik78se** [comment]
I've tried the 0.9.2 version and it seems to work now.

However, when I run "run-action" from the GUI, the output seems limited to the "message" somehow.

Would you consider showing more of the data bag returned from the action or is it deliberately not showing the full action output? This seems fairly arbitrary and less of an experience from someone using the GUI imo.

**Comment by hatched** [comment]
Yes this is a limitation of the current implementation, the full design actually has all the various outputs available (even for download) We won't be able to start on this full implementation for a number of months yet though.

Here is a mockup:
![III  Action logs - Default view](https://user-images.githubusercontent.com/532033/145469036-c3a83604-d013-4926-86cf-b2ce6779c74a.png)

**Comment by erik78se** [comment]
What should I set to show a string now then? I use this for now, but I don't get anything

            event.set_results(results={'session-key': key})
