### ISSUE TITLE
Not possible to upgrade from 0.8.1 to 0.9.2 !!!! 

### ISSUE THREAD

**Issue by moula** [canonical-web-and-design/jaas-dashboard#1200]
moula@maas1:~$ juju dashboard 
Dashboard 0.8.1 for controller "juju-controller01" is enabled at:
  https://10.0.1.190:17070/dashboard
Your login credential is:
  username: admin
  password: d5abf5a80abd9d65597de193bff0a0d2
moula@maas1:~$ juju upgrade-dashboard 
Juju Dashboard at version 0.8.1

**Comment by hatched** [comment]
0.9.2 is not yet released on simplestreams so if you want to upgrade you'll have to download the tarball from github.

then run `juju upgrade-dashboard ./path/to/tarball`.
