### ISSUE TITLE
Dashboard icons are returning a 404 or 503 on lookup

### ISSUE THREAD

**Issue by cyberm4g3** [canonical-web-and-design/jaas-dashboard#1210]
**Describe the bug**
In testing out juju & charmed kubernetes, I noticed that all of the app icons in the dashboard aren't loading. Looking further I found the url they're trying to load from (examples below), and hitting that directly results in either a 404 Not Found or a 503 Service Unavailable. My juju controller is version 2.9.22.

https://api.jujucharms.com/charmstore/v5/~containers/containerd-200/icon.svg
https://api.jujucharms.com/charmstore/v5/keystone-330/icon.svg
https://api.jujucharms.com/charmstore/v5/~containers/kubernetes-worker-838/icon.svg

**Screenshots**
![image](https://user-images.githubusercontent.com/53304596/153425004-17398175-4cad-42b2-8732-c3e8219bc3f4.png)

**Comment by cyberm4g3** [comment]
Is this related to the charmhub transition (link below)? I _just_ started trying out yesterday, which is when the article says the transition was supposed to happen.

https://discourse.charmhub.io/t/charmhub-transition-faq/5636/9

**Comment by gfenoy** [comment]
I think @cyberm4g3 is correct about the charm hub transition.

Nevertheless, I still get the exact same issue. So, I used the following commands to get the icons shown from the UI:

````
# SSH on the controller 0 to update juju dashboard JavaScript
juju ssh -m controller 0
# From the SSH session
cd /var/lib/juju/gui/925d99bcc83bb9accc88df729d12e5c83a07ece73a94f936fbbae959184ac12d/static/js/
cp main.877f0846.chunk.js main.877f0846.chunk.backup
sed 's#return`https://api.jujucharms.com/charmstore/v5/${e=e.replace("cs:","")}/icon.svg`;#return`https://charmhub.io/${e=e.replace("cs:","").replace("~containers/","").replace("kubernetes-master","kubernetes-worker").split("-").slice(0,-1).join("-") }/icon`;#g' -i main.877f0846.chunk.js
exit
````

Once the UI is reloaded, it should display icon properly.

It is a very simple fix using a charmhub.io link, when the transition is over, you can ssh back and copy back the backup javascript file.
