### ISSUE TITLE
WebCLI deploy command failing

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/jaas-dashboard#1218]
When running `juju deploy` via the webCLI in an JIMM/Candid environment the command fails with an auth error.
 
The code seems to be in src/components/WebCLI/WebCLI.js .. but the way i read the code the websocketURL would either be null or ${protocol}://${controllerWSHost}/model/${modelUUID}/commands

**Comment by alesstimec** [comment]
fixed https://github.com/juju/juju/pull/13827

**Comment by anthonydillon** [comment]
Thanks for updating this issue @alesstimec would you be happy for us to close this issue now with the upstream fix in place?

**Comment by alesstimec** [comment]
Yes, please close the issue
