### ISSUE TITLE
Listing page: Remove "Click to view full details" for something more meaningful and realistic

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#136]
As discussed, for the error messages in the model list view.

**Comment by cristinadresch** [comment]
@hatched can you add size to this one please. and what message you're planning to use? can you review it with @clagom please

**Comment by hatched** [comment]
It'll be the first message from an entity in error. 

There are multiple different places that can report an error; model, application, unit, machine... So the first one that the internal parser runs into with a "message" will be what is shown here.
