### ISSUE TITLE
Typography is not consistent with design

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#139]
Titles are 12px by design, bigger in the implementation:
![Screenshot 2019-10-31 at 10.05.34.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/134bbe35-80b5-4050-913d-0e11bfdf27a1)

**Comment by spencerbygraves** [comment]
@clagom @barrymcgee I made the titles 12px in the design as this will be a vanilla update. (I thought it was in already, but Lyubo is going to make a PR soon).

So, I'll close this for now and we will get the update later.
