### ISSUE TITLE
Details page: Indentation for units

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#147]
Units need to be indented when there's a second level relation, per design:
![Screenshot 2019-10-31 at 11.31.37.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/1b4f6d5c-b0b4-40fb-b8de-fd1ced23c322)

![Screenshot 2019-10-31 at 11.31.31.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/cc3b70ce-4565-484f-b91c-e4e61161e402)

**Comment by cristinadresch** [comment]
This is lower priority

**Comment by hatched** [comment]
Fixed by #203
