### ISSUE TITLE
Details page: Icons should be all round, masked - Model detail page view

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#149]
As per design:
![Screenshot 2019-10-31 at 11.35.14.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/c4437b28-a43e-4d82-bb48-8dc11d242a2a)

![Screenshot 2019-10-31 at 11.35.19.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/926baa29-ed21-4e56-965a-357409ce3218)

**Comment by spencerbygraves** [comment]
![image](https://user-images.githubusercontent.com/9105999/68020876-bcd75280-fc97-11e9-8f86-924e128de2d5.png)
