### ISSUE TITLE
Update spacing in the left navigation

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#163]
The left navigation should have 16px padding to the left of the icons, so that when the navigation is closed the icons remain centred in the 48px wide strip:

**Currently it's slightly off:**

![image](https://user-images.githubusercontent.com/9105999/68025265-47be4a00-fca4-11e9-9064-1028bc2bdbd5.png)

**Compared with the design:**

![image](https://user-images.githubusercontent.com/9105999/68025325-5f95ce00-fca4-11e9-8ee9-593f221489c4.png)

Also, when the navigation is closed, I moved the logo to the left a bit, to be centred in the 48px strip. You can also see that above. Can we try to do that please, otherwise the closed nav looks a bit wonky:

![image](https://user-images.githubusercontent.com/9105999/68025463-b1d6ef00-fca4-11e9-84e3-92a6bfd73b9a.png)

Thanks!

**Comment by hatched** [comment]
I'm not sure there is enough space between the right of the logo and the "JAAS" text to make this work. We may have to transition to a different logo when it's closed.

**Comment by spencerbygraves** [comment]
@hatched I can supply a logo without the text. Can we then swap the logo when it animates?

**Comment by anthonydillon** [comment]
If we use an inline SVG we could manipulate (hide, fade out) the text in the logo without swapping the asset.

**Comment by clagom** [comment]
I think Zenhub column does a good job, changes logo as well, look at:
https://app.zenhub.com/workspaces/juju-squad-593fe9c0b747921fa7ecd561/board?filterLogic=any&repos=14960387,26931469,94216425,143756215,172533571,188024450,175492049,199520078,209070242&showPipelineDescriptions=false

**Comment by barrymcgee** [comment]
Fixed in https://github.com/canonical-web-and-design/jaas-dashboard/pull/174
