### ISSUE TITLE
Model error count off center

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#168]
<img width="247" alt="Screen Shot 2019-11-01 at 10 27 48 AM" src="https://user-images.githubusercontent.com/532033/68039713-54d23d80-fc92-11e9-831f-f0e4159ee66b.png">

**Comment by barrymcgee** [comment]
This was caused by the text size increase at larger resolutions as inherited by Vanilla. This has now been removed.
