### ISSUE TITLE
Unknown icon is not totally circular

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#171]
![68129350-4c3b6a80-ff11-11e9-8fc7-896395d8203b](https://user-images.githubusercontent.com/505570/68130646-a1787b80-ff13-11e9-920c-6d7e1e67e1f6.png)

**Comment by spencerbygraves** [comment]
@barrymcgee here you go...

[Unknown icon.svg.zip](https://github.com/canonical-web-and-design/jaas-dashboard/files/3804601/Unknown.icon.svg.zip)

**Comment by hatched** [comment]
This has been resolved.
