### ISSUE TITLE
Details page: Truncate long messages

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#175]
Truncate the long messages in the details page by collapsing the column using a chevron.

**Comment by barrymcgee** [comment]
@hatch Has this been validated by design? If so, is there a visual? @spencerbygraves

**Comment by spencerbygraves** [comment]
@barrymcgee There is a design for expanding the row to show the message in [this issue](https://github.com/canonical-web-and-design/juju-squad/issues/981).

> Truncate the long messages in the details page by collapsing the **column** using a chevron.

@hatched did you mean row rather than column? I haven't done a design for collapsing columns.

**Comment by hatched** [comment]
@barrymcgee yep see the linked issue right below the issue description.
