### ISSUE TITLE
Model detail page / Responsiveness breaking point for 15" laptop

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#179]
Can we tweak the breaking point media queries for the responsive layout at 1580 instead 1680 in order to have the extended layout on 15" laptop screen?

At the moment in 1680 resolution I already see the smaller topology column.

**Comment by clagom** [comment]
CC @cristinadresch

**Comment by cristinadresch** [comment]
@barrymcgee any thoughts on this one?
