### ISSUE TITLE
Model detail page / Responsiveness breaking point affects typography 

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#180]
I wouldn't change the size of the typography from 1680 breaking point:

> 1680:
![Screenshot 2019-11-05 at 12.08.51.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/7b7fb491-46e3-4c06-9850-b504a638f9a4)

< 1680:
![Screenshot 2019-11-05 at 12.08.57.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/aec44e5d-6bdd-4c81-9e94-dd191ffd2955)

I would keep the same size

CC @spencerbygraves @cristinadresch

**Comment by barrymcgee** [comment]
@clagom @spencerbygraves I'm not changing any typography, 1680px is the Vanilla "Large desktop" breakpoint so the typography changes are being inherited from upstream.

**Comment by clagom** [comment]
@barrymcgee I'm pretty sure it's an option you can switch on and off in Vanilla
@spencerbygraves CC @lyubomir-popov 
They did switch this off in MAAS

**Comment by spencerbygraves** [comment]
Yes, I believe it's an optional thing. Ping @lyubomir-popov for the details. Makes sense to not increase the size here.

**Comment by lyubomir-popov** [comment]
@barrymcgee  You can set [`$increase-font-size-on-larger-screens`](https://github.com/canonical-web-and-design/vanilla-framework/blob/ea6f05b4a90169b36a5e9c5a86ceae40cbddd986/scss/_settings_font.scss#L8) to `false` to disable it.

**Comment by barrymcgee** [comment]
@lyubomir-popov OK, great but is it correct to say this setting is totally undocumented? I can't find it on the docs site and grepping he codebase, it doesn't appear in any markdown files?

<img width="679" alt="Screenshot 2019-11-05 at 15 36 42" src="https://user-images.githubusercontent.com/505570/68221951-24680780-ffe2-11e9-87be-5d210d54d316.png">

**Comment by lyubomir-popov** [comment]
@barrymcgee true. I've made a [PR](https://github.com/canonical-web-and-design/vanilla-framework/pull/2624) to remedy that.

**Comment by barrymcgee** [comment]
@lyubomir-popov Great, thank you 🙏🏻

**Comment by cristinadresch** [comment]
@barrymcgee so this one is ok to be done now?
