### ISSUE TITLE
Details Page: Extra spacing between header and content

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#208]
App:
<img width="212" alt="Screen Shot 2019-11-13 at 9 16 28 AM" src="https://user-images.githubusercontent.com/532033/68787413-5686f400-05f6-11ea-8c59-1be0d65ebf0b.png">

Design:
<img width="174" alt="Screen Shot 2019-11-13 at 9 17 12 AM" src="https://user-images.githubusercontent.com/532033/68787436-64d51000-05f6-11ea-9cdc-b316d0ed842d.png">

**Comment by barrymcgee** [comment]
This is a weird CSS Grid inconsistency where the `<thead>` element is adding phantom space in Firefox.

Chrome - 28px high (correct)

<img width="486" alt="Screenshot 2019-11-14 at 15 28 37" src="https://user-images.githubusercontent.com/505570/68871093-d3e45e80-06f3-11ea-9e72-e8db74d9f02f.png">

Firefox - 34.2px high (incorrect)

<img width="612" alt="Screenshot 2019-11-14 at 15 29 13" src="https://user-images.githubusercontent.com/505570/68871149-e9598880-06f3-11ea-83d7-cd67d207e12d.png">
