### ISSUE TITLE
After logging out my models still display in the background.

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#218]
Before logging in there are no models:

![image](https://user-images.githubusercontent.com/9105999/69068742-32c01580-0a1d-11ea-908a-636cf138525f.png)

After logging out my models still display in the background:

![image](https://user-images.githubusercontent.com/9105999/69068648-0c01df00-0a1d-11ea-9cdd-77a3e01e50e2.png)

**Comment by hatched** [comment]
Dev note: The `modelData` needs to be cleared and to disable fetching. All fetching will fail at this point anyways because the authentication data has been purged. But a bunch of failed requests isn't very good :)

**Comment by cristinadresch** [comment]
@hatched what is the latest on this one?

**Comment by hatched** [comment]
I'll be working on it again to address review comments from the pr tomorrow.
