### ISSUE TITLE
App name column too narrow

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#223]
<img width="244" alt="Screen Shot 2019-11-19 at 12 12 33 PM" src="https://user-images.githubusercontent.com/532033/69173706-ec72c100-0ac5-11ea-802d-24fc4832a2de.png">

We have a lot of available white space to dedicate some free space to the app column but we'll also need to address the overflow.

@spencerbygraves

**Comment by clagom** [comment]
The design already present a wider column for apps names (and units and so on). I would try to match the width of the columns (also the other ones) from the design as much as possible

**Comment by spencerbygraves** [comment]
@hatched you can see designs for model details [here](https://app.zeplin.io/project/5d2dfd8e5b67f14c5e1d2aef/dashboard?seid=5daf28a2acac1022bcdc88da). Thanks.
