### ISSUE TITLE
Adjust the icon size and position in models table

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#229]
The icons for apps, units and machines in the models table are a bit small and vertically off centre. Please can they be updated to match the design.

**Currently**

![image](https://user-images.githubusercontent.com/9105999/69351349-14535780-0c73-11ea-8e6c-8172edf1d5d0.png)

**Design**

![image](https://user-images.githubusercontent.com/9105999/69351383-26cd9100-0c73-11ea-9284-5404c27730f5.png)

**Comment by cristinadresch** [comment]
@barrymcgee all good to finish this one by tomorrow?

**Comment by barrymcgee** [comment]
@cristinadresch yep, on course!
