### ISSUE TITLE
Investigate JAAS HTTP api

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#236]

**Comment by cristinadresch** [comment]
@hatched are you working on this? are you going to be able to complete the investigation by end of this week?

**Comment by hatched** [comment]
I am, and I'll know if I'll be done in 2 days :-)

**Comment by cristinadresch** [comment]
@hatched cool, if you are working on it can you move this to in progress then please. if you're not done I would suggest breaking this down further as 'investigate' is pretty vague

**Comment by hatched** [comment]
Yep I was just waiting until I actually started on it to move it.

I don't know what I don't know to break this down further :-) But I'll definitely be creating follow-ups using what I've learned.
