### ISSUE TITLE
Integrate GA and settings

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#245]
Add event hooks to important events.

**Comment by cristinadresch** [comment]
@hatched now that we have released it I'm adding this to next iteration

**Comment by clagom** [comment]
This is an epic now, we can add issue for 
- adding GA
- settings page to disable GA
Thanks @hatched please estimate both when you created them

**Comment by cristinadresch** [comment]
@hatched should we carry forward some of these to next iteration?

**Comment by barrymcgee** [comment]
@cristinadresch @hatched PR here: https://github.com/canonical-web-and-design/jaas-dashboard/pull/356
