### ISSUE TITLE
Adjust table column widths

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#256]
Can we adjust some of the column widths to better match the designs please.

For example, on the models list we could reduce the gap between the CLOUD/REGION and CREDENTIAL columns to give more space to the first column.

[Models list design](https://zpl.io/beOAPkq)

And on the details page we can reduce the space between the STATUS and VERSION, and STORE and REV columns to give more room to the first column.

[Model details](https://zpl.io/VOpxL7r)

**Comment by barrymcgee** [comment]
@spencerbygraves Can you give an indication of how you split these columns by percent please?

**Comment by spencerbygraves** [comment]
@barrymcgee well, I'd say around 20-25% for the first column. And then generally I space them according to the content.

**Comment by hatched** [comment]
I completed this in another PR.
