### ISSUE TITLE
Button group component should be generalized

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#262]
We should split the `ModelGroupToggle` component and create a `ButtonGroup` component out it.

The ButtonGroup section would likely become this part: https://github.com/canonical-web-and-design/jaas-dashboard/blob/master/src/components/ModelGroupToggle/ModelGroupToggle.js#L13-L27 With the buttons and functions being passed in as props.

The remaining wrapper elements and label should probably not be part of the component at all as I imagine the label could move around depending on the use case.

https://github.com/canonical-web-and-design/jaas-dashboard/tree/master/src/components/ModelGroupToggle

**Comment by anthonydillon** [comment]
There is no ModelGroupToggle in the codebase  so this must be done
