### ISSUE TITLE
Update icons on the side navigation

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#286]
We use the same icons for models and controllers and for apps and units, we should change 'models' and 'controllers' with a different set.

**Comment by spencerbygraves** [comment]
@clagom we should get these icons designed as part of the new set, but if we want to change them temporarily I suggest something like the ones below.

![image](https://user-images.githubusercontent.com/9105999/72731291-56bde580-3b8b-11ea-970c-d83dbbf5ea89.png)

**Comment by clagom** [comment]
I would say we can change them with the ones you display here (if you can give the asset to Barry or Jeff), and then we update with the new set if necessary. At the moment we use the same ones and it's confusing.

**Comment by spencerbygraves** [comment]
@clagom, thanks. I'll open an issue to update the icons.

**Comment by cassiocassio** [comment]
Concerning the future icons, not these ones...

We should lightly user-test the future proposed icons for these - making distinct meanings for these these is pretty tricky. 

There's probably a need for a pods icon too - we'll need to represent k8s workloads inside jaas at some point. If Mr Hicks is thinking about units and machines the brief could include pods and other k8s concepts we need at the same time.
