### ISSUE TITLE
Unable to log in after logging out without refresh

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#289]
Doesn't update the page

**Comment by hatched** [comment]
This issue doesn't make a whole lot of sense :-)

When I log out it correctly logs out but then after going through the USSO login again it does not reconnect and start fetching data.

**Comment by hatched** [comment]
This is only an issue when the controller uses an external identity provider like USSO on JAAS. 

The u/p flow works as expected.
