### ISSUE TITLE
No favicon on the dashboard

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#291]
The dashboard doesn't display the favicon in the browser

**Comment by hatched** [comment]
This has been resolved

**Comment by barrymcgee** [comment]
Not on this side of the pond...

<img width="934" alt="Screenshot 2020-01-29 at 11 09 14" src="https://user-images.githubusercontent.com/505570/73351904-e3e9f400-4287-11ea-8637-68822778de60.png">

Please see the referenced pull request on jaas.ai for my proposed solution.

**Comment by hatched** [comment]
Ok now it's fixed :)
