### ISSUE TITLE
Change filter label to “filter models”

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#294]
At the moment we display 'filter terms':
![Screenshot 2020-01-20 at 10.06.24.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/62ba32f8-21ad-459e-9e7a-cdf6b7f6861d)

Please change it to “filter models”

**Comment by hatched** [comment]
Sure, but the models page is the only page that has a filter input :-) 

Closing this until we have somewhere that this can be implemented.

**Comment by clagom** [comment]
Changing the scope then, still valid

**Comment by hatched** [comment]
Closing then as it's already been completed :-D

see: https://dashboard.staging.jaas.ai/models
