### ISSUE TITLE
Update side navigation icons

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#296]
Please update the icons for Models and Controllers.

Design issue - https://github.com/canonical-web-and-design/jaas-dashboard/issues/286

[Icons.zip](https://github.com/canonical-web-and-design/jaas-dashboard/files/4087119/Icons.zip)

**Comment by barrymcgee** [comment]
@spencerbygraves Did you ever install the [Sketch SVGO plugin](https://www.sketch.com/extensions/plugins/svgo-compressor/)?

Doing so would mean assets such as these would be automatically compressed as you export them.

**Comment by spencerbygraves** [comment]
Thanks @barrymcgee, I'll give that a go.
