### ISSUE TITLE
Dot is black, should be orange or grey

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#308]
The colour depends on how we organise this error, but the black colour is not in use anymore.

![Screenshot 2020-01-22 at 16.19.07.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/e80ea9db-de8a-4d74-8ba7-5d1e79302374)

**Comment by hatched** [comment]
So which should it be? Orange or grey? :-)

**Comment by hatched** [comment]
I was thinking it should actually be red as it's an error state.

**Comment by clagom** [comment]
Yes. Definitely not black ;)

**Comment by barrymcgee** [comment]
@clagom so.. red?

**Comment by spencerbygraves** [comment]
@barrymcgee yes, we're using red for errors.
