### ISSUE TITLE
Visual QA for the side nav

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#326]
@spencerbygraves could you review this and give the specs to Barry or Jeff for the changes in order to match the design?
Implementation:
![Screenshot 2020-01-30 at 13.57.49.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/a5b31a05-a1c5-40fc-8ad4-a100dd1ac999)

Design:
![Screenshot 2020-01-30 at 13.59.08.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/f00420ec-a1b2-499a-9758-c583b27a1b90)

**Comment by spencerbygraves** [comment]
The design can be found [here on Zeplin](https://zpl.io/2jR9Yrp).

It looks like we need to double check the text colour, and the width and colour of the horizontal line.

Issues #306 and #307 are also related to this.

@clagom are you happy to not have a version icon, and not visible when the nav is collapsed?
