### ISSUE TITLE
Configuration icons disappeared

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#327]
Applications and units icons are not visible on latest master and staging:
![Screenshot 2020-01-30 at 14.00.24.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/d1a224fa-cf0c-4b09-bed3-12ea9941c8e8)

**Comment by spencerbygraves** [comment]
@barrymcgee looks like the icons are there, but are the ones from the left hand navigation, not the ones for apps and units:

![image](https://user-images.githubusercontent.com/9105999/73463051-913a3600-4374-11ea-96f6-513a06cf215d.png)
