### ISSUE TITLE
Functionality when clicking on top pills (apps, units, machines, relations)

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#334]
<img width="635" alt="Top-filtering" src="https://user-images.githubusercontent.com/47972694/73070674-96e9d480-3eb9-11ea-86b7-1855f375838d.png">

Top filtering options

**Comment by clagom** [comment]
Please estimate @barrymcgee

**Comment by cristinadresch** [comment]
@barrymcgee @hatched guys should we move this one to next iteration?

**Comment by cristinadresch** [comment]
@barrymcgee to add topology toggle

zeplin: 009 - Dashboard - models details view topology off
https://app.zeplin.io/project/5d2dfd8e5b67f14c5e1d2aef/screen/5daf27f9e0e5042c2d26bae2
