### ISSUE TITLE
Change the icon to expand the topology

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#340]
Can we change the icon for expanding the topology to [this one](https://assets.ubuntu.com/v1/c566f22e-fullscreen-grey_16.svg), also used on https://maas.io/tour.

In this context, `p-icon--expand` may be confused with adding something.

**Before**
![image](https://user-images.githubusercontent.com/9105999/73657910-2433e280-468b-11ea-9af2-37e5c185ea73.png)

**After**
![image](https://user-images.githubusercontent.com/9105999/73658306-02872b00-468c-11ea-9d03-4ef368929b35.png)

Thanks.

**Comment by spencerbygraves** [comment]
We'll add a new fullscreen icon to Vanilla instead.

**Comment by hatched** [comment]
Sure, this should be a common icon across our projects. Please file an issue and have it added to vanilla then we can easily add it here.
