### ISSUE TITLE
Link titles from apps names should link to the relevant charm page

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#348]
E.g. in the screenshot, clicking on 'client' should open: https://jaas.ai/hadoop-client/12 and CharmHub in the future
![Screenshot 2020-02-04 at 16.57.18.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/c8f07d8f-c414-4d13-b7b0-b18944f15f17)

**Comment by barrymcgee** [comment]
@hatched How is it possible to construct a link to the charm store using the info we have here? Inspecting each app, we have a `charm` property associated with each app but it seems unreliable?

<img width="535" alt="Screenshot 2020-02-27 at 14 30 20" src="https://user-images.githubusercontent.com/505570/75454674-b4550700-596d-11ea-82f0-83ea7e959795.png">

**Comment by anthonydillon** [comment]
Take `charm` and replace cs: with empty string and then replace the dash before the version with a forward slash. To become: `https://jaas.ai/ganglia/12`. Also, check none verified charms as they need to be prefixes with the user.

**Comment by barrymcgee** [comment]
@anthonydillon For ref, this is the lib util I needed: https://github.com/juju/jaaslibjs/blob/master/lib/urls.js
