### ISSUE TITLE
When running in Juju use Juju logos

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#355]

**Comment by hatched** [comment]
Based on a configuration value, if we're running in a bootstrapped Juju controller then use the Juju, not JAAS logos.

**Comment by spencerbygraves** [comment]
@hatched @clagom looking back at the email conversation, was this agreed?

**Comment by hatched** [comment]
It was offline.

**Comment by barrymcgee** [comment]
@hatched By configuration value, do you mean an environment variable in `.env`? If so, what would it be called?

@spencerbygraves Is this the logo we would use? https://assets.ubuntu.com/v1/e2ac88af-juju_black-orange_hex.svg

**Comment by hatched** [comment]
@barrymcgee no its a configuration value in the `config.js` template that I'm currently working on. The `.env` file will no longer be used for application configuration.

**Comment by hatched** [comment]
@spencerbygraves could I get the link above that @barrymcgee provided split up to contain just the text so that I can toggle the `JAAS` version?

Existing JAAS version: https://github.com/canonical-web-and-design/jaas-dashboard/blob/master/src/static/images/logo/logo-text.svg

**Comment by spencerbygraves** [comment]
@hatched https://assets.ubuntu.com/v1/6d382a53-image-juju-256.svg

**Comment by spencerbygraves** [comment]
@hatched text only - https://assets.ubuntu.com/v1/a85f7947-juju_black-text-only.svg

**Comment by hatched** [comment]
Thanks @spencerbygraves
