### ISSUE TITLE
User menu when navigating

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#366]
When you open the user menu in the left sidebar and click 'settings' it snaps closed. It might be nice if it either stayed open on those types of panes, or animated back closed. 

When you click the settings link if you're already in the settings view it stays open.

**Comment by spencerbygraves** [comment]
I think it should behave in the same way as the jaas menu at the top; staying open until the user closes it, or closing when the user selects something else.

At the moment the jaas menu snaps closed when you select models or controllers. It would be nice if it animated in the same way that it opens.

You can see this in the [zenhub left nav](https://app.zenhub.com/workspaces/juju-squad-593fe9c0b747921fa7ecd561/board?repos=94216425,143756215,135745787,136221662,199520078&showPipelineDescriptions=false)

By the way, I think the user menu will change in future. @clagom and I had talked about it working with a contextual menu as it did in the top right of the screen, or as it does bottom left in Zenhub. @barrymcgee has built it like this for now as I wasn't completely sure about the design, which I will look at again.

**Comment by clagom** [comment]
Yeah we should fix this:
![Screenshot 2020-02-24 at 09.27.30.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/e9d9f294-e377-4422-b0b7-d2358c13516b)
And do the same as the JAAS menu on top, as @spencerbygraves said. When the menu side bar is collapsed, the user menu closes. When you mouseover hover it, it expands (if previously opened). Just like the JAAS bit on top basically.
I agree that in settings page the side bar navigation should probably stay open and show the settings as active / highlighted just as for models when you are in model page view.

**Comment by clagom** [comment]
Reassigning back to @hatched and @barrymcgee.
@spencerbygraves please have a look because I think it still needs visual QA as the sidebar and links are different from the design.

**Comment by barrymcgee** [comment]
@hatched Does it make sense at this stage to create a "UI" object in the redux store to store bools such as `settingsMenuActive` and `sideMenuActive`?

**Comment by hatched** [comment]
As discussed offline, we're going to create another top level key `ui` to keep ui state changes separate from data changes in other portions of the store.

**Comment by spencerbygraves** [comment]
For now can we make the version number text 16px to match all the other text.

@bartaz will be starting to build the new Vanilla side navigation next iteration, which I would like to use here when done.

Thanks.
