### ISSUE TITLE
Do not show model row until `info` arrives

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#367]
If a user has a filter applied that requires data from the `modelInfo` call then the model row is briefly shown before the data arrives. So we need to hide the model rows until the `modelInfo` data is available.

**Comment by barrymcgee** [comment]
@hatched Took a quick look at this - given we use `MainTable` from `react-components`, does that not mean the most granular level we can conditionally gate is the entire table rather than a per row basis?

**Comment by hatched** [comment]
No we just filter the row at the data that's going into the table so if values aren't defined we delete the entire row.

**Comment by hatched** [comment]
I'm going to close this as a non-issue as it wont be with the new watcher.
