### ISSUE TITLE
Toggle view filters in the model details page should update the URL

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#374]
These toggle buttons do not currently update the URL so this preference cannot be shared.

<img width="771" alt="Screenshot 2020-02-28 at 13 06 34" src="https://user-images.githubusercontent.com/505570/75551109-571f8b00-5a2b-11ea-93c3-c8a9748243e8.png">

**Comment by hatched** [comment]
This has been completed with the new view toggles.
