### ISSUE TITLE
config.js file not loaded from root path on other pages

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#380]
If you try and load the app from a page that's not `/` it'll try and load `config.js` from that path.

ex) `https://dashboard.staging.jaas.ai/models/gomboli@external/config.js` and not `https://dashboard.staging.jaas.ai/config.js`

<img width="1267" alt="Screen Shot 2020-03-12 at 8 29 57 PM" src="https://user-images.githubusercontent.com/532033/76583979-4269db00-64a0-11ea-8566-29a2797324d5.png">

**Comment by barrymcgee** [comment]
@hatched I'm seeing this every time I hit save and the app refreshes:

<img width="964" alt="Screenshot 2020-03-18 at 11 48 06" src="https://user-images.githubusercontent.com/505570/76957922-98120d80-690e-11ea-8448-2920051c098c.png">

**Comment by hatched** [comment]
Is the URL `/`?
