### ISSUE TITLE
Provide login failure feedback

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#388]
If login fails whether from an external identity provider or u/p there is no indication in the UI of a problem.

**Comment by hatched** [comment]
Related: https://github.com/canonical-web-and-design/jaas-dashboard/issues/387

**Comment by barrymcgee** [comment]
@hatched Can you provide further instructions on how to replicate this behaviour?

**Comment by hatched** [comment]
There are a number of different failure cases, but for example, entering invalid credentials.
