### ISSUE TITLE
Config file not loading in production

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#391]
https://jaas.ai/models

<img width="1506" alt="Screenshot 2020-03-25 at 10 20 02" src="https://user-images.githubusercontent.com/505570/77527012-5be92a80-6e83-11ea-8a49-ad66a2af5ed9.png">

**Comment by barrymcgee** [comment]
https://github.com/canonical-web-and-design/jaas.ai/pull/520

**Comment by hatched** [comment]
Closing as duplicate of #389
