### ISSUE TITLE
Terminal resizing should/could use React events pattern

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#397]
Ref: https://github.com/canonical-web-and-design/jaas-dashboard/pull/394

As per the above PR, the event listeners for are placed directly on the window object when it's preferable they are placed directly on the component. 

We (@hatched and I) tried to refactor this in a time-boxed period but events were not firing. This issue requires further investigation.

**Comment by hatched** [comment]
This Component has been rewritten so this issue is no longer necessary.
