### ISSUE TITLE
App column to narrow and content overlapping with the next one

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#424]
I think this is a regression, the width of the 'app' column was wider before. Now it's narrow, and on smaller width the content overlaps with the next column:

![Screenshot 2020-04-14 at 20.28.03.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/b7eb2b77-3c74-40a5-8e32-2063deaef24d)

![Screenshot 2020-04-14 at 20.28.07.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/e0a1f29c-2dc4-4545-b558-571b9c0d3787)

**Comment by hatched** [comment]
Do we want to fix the application name column to a minimum width? The width of the longest un-wrappable name?

**Comment by clagom** [comment]
Yes that would do. I think @spencerbygraves has some values from his design that we can apply.

**Comment by hatched** [comment]
Related #223

**Comment by spencerbygraves** [comment]
@clagom @hatched I have 270px in the design. We could try that and see if it's better.

**Comment by clagom** [comment]
Sounds good
