### ISSUE TITLE
Fix the logo spacing

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#440]
There is a larger gap between the logo and the text in the top right to accommodate the collapsible sidebar. To remedy this we could animate the gap closer when the sidebar is open.

Re: https://github.com/canonical-web-and-design/jaas-dashboard/pull/431#issuecomment-616412388

**Comment by anthonydillon** [comment]
Without milestone this work will not be recorded/tracked for the squad. Just a heads up.
