### ISSUE TITLE
Demos do not work

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/jaas-dashboard#443]
**Describe the bug**
Demos on PRs do not work. These are important for keeping reviews fast.

**To Reproduce**
Check the dem link on any PR

**Expected behavior**
Each PR from the team should generate a working demo.

**Comment by hatched** [comment]
@jpmartinspt took a look at this and found that once the dashboard is built in the container it's immediately shut down. Running the server manually while ssh'd into the container works on the demo server and they also work locally. 

The PR that introduced this breakage is: https://github.com/canonical-web-and-design/jaas-dashboard/pull/401

**Comment by hatched** [comment]
This may persist until we're able to remove `craco` entirely. To remove `craco` we need to replace the jujulib code which is scheduled for early this cycle.
