### ISSUE TITLE
Elements on settings page appear to float randomly

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#464]
@spencerbygraves @clagom 

This page needs some design love :) Should the switch align with the banner?

<img width="1279" alt="Screenshot 2020-04-27 at 20 26 40" src="https://user-images.githubusercontent.com/505570/80412252-80db1e00-88c5-11ea-81aa-775123709973.png">

**Comment by spencerbygraves** [comment]
@barrymcgee @clagom I wonder if we need the large notification here. We could use small text, as we would do [under an input field](https://vanillaframework.io/docs/base/forms#inline). It might also be better if we add more controls.

What do you think?

![image](https://user-images.githubusercontent.com/9105999/81069406-bdb49f80-8ed9-11ea-9082-9971fa09bba7.png)

**Comment by clagom** [comment]
I agree @spencerbygraves.
Although I'm not sure what else we could add at this point

**Comment by hatched** [comment]
We'll be adding an input field to set the location of the Juju Shell in the near future.

**Comment by cristinadresch** [comment]
@spencerbygraves do you want to propose a final design for this? adding it to backlog/maintenance for now

**Comment by spencerbygraves** [comment]
@cristinadresch I think the design above is good for the amount of content we have.

**Comment by spencerbygraves** [comment]
@barrymcgee @hatched It would be good if we can look at this for 2.8 please.

Thanks.
