### ISSUE TITLE
Clicking log out nukes table data but does not log out

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#465]
- Log in
- Click 'Settings > Log out" 
- The table data disappears but the user still appears logged in

<img width="1694" alt="Screenshot 2020-04-27 at 20 37 33" src="https://user-images.githubusercontent.com/505570/80413632-a701bd80-88c7-11ea-82dc-26c917d0fae9.png">

**Comment by hatched** [comment]
I'm actually working on this right now. The issue is that the logic used to determine if the user is logged in in the UI is no longer correct. The user is logged out, it's just the UI that hasn't updated.
