### ISSUE TITLE
Beta label padding is wrong

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#469]
The Alpha label has too much space at the bottom. [Vanilla version](https://vanillaframework.io/docs/patterns/labels#new) on the right

![image](https://user-images.githubusercontent.com/9105999/80809596-e840e880-8bb9-11ea-89b7-5f1a9aa59bb1.png)

**Comment by spencerbygraves** [comment]
![image](https://user-images.githubusercontent.com/9105999/80809746-3a820980-8bba-11ea-8956-4d3f35bb6281.png)

**Comment by spencerbygraves** [comment]
@hatched @barrymcgee this still has the wrong padding on the live dashboard, will it be updated soon?

**Comment by hatched** [comment]
Looks like you're looking at an old version of the dashboard. The current version is 0.1.3 and this issue is resolved there.

**Comment by spencerbygraves** [comment]
@hatched will that be in the 2.8 release?

**Comment by hatched** [comment]
Yes, it's already in the Juju 2.8 rc. If you run the dashboard from source you'll see it.
