### ISSUE TITLE
Release notification appears before user has logged in

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#498]
<img width="1440" alt="Screenshot 2020-05-21 at 11 45 20" src="https://user-images.githubusercontent.com/505570/82551691-935d1600-9b58-11ea-9238-34f4a1992e2b.png">

**Comment by hatched** [comment]
I don't think this is a bug, they are landing on a new UI. The bug may simply be that it's behind the mask.

**Comment by barrymcgee** [comment]
Presenting readable text gives an expectation it should be read... as it's masked, the color contrast makes it barely legible and the link is unclickable. It's irrelevant information until they log in as they can't provide feedback on something they can't access.

**Comment by hatched** [comment]
I think that a notification that they have landed on the replacement for the GUI instead of the GUI before logging in would be important information.

**Comment by spencerbygraves** [comment]
I wouldn't expect to see the notification until I've logged in. It feels odd to welcome someone and ask for feedback before that.

Tell the user it's a new thing when they can see the new thing.
