### ISSUE TITLE
Clicking on model name results in "Something has gone wrong"

### ISSUE THREAD

**Issue by ianmjones** [canonical-web-and-design/jaas-dashboard#515]
**Describe the bug**
Version Juju 2.8-rc2 (snap) / Dashboard 0.1.3 (beta)

When I click the name of my non-controller model in the Models area, in this case "gm-dev"...

![Screenshot from 2020-05-27 09-16-58](https://user-images.githubusercontent.com/4710/82995107-15d35300-9ffb-11ea-9493-01ec15248c42.png)

... I get the following error message...

![Screenshot from 2020-05-27 09-16-18](https://user-images.githubusercontent.com/4710/82995356-65b21a00-9ffb-11ea-90e6-bab57814e1d4.png)

This happens every time, above screenshot includes devtools console in case that helps.

This was with an upgrade from 2.7.6 to 2.8-rc2, following upgrade guide from https://discourse.juju.is/t/juju-2-8-rc2-release-notes/3061, which had no problems. Then running `juju upgrade-gui` to pick up new dashboard.

The `gm-dev` model is a simple deploy of https://github.com/dshcherb/cockroachdb-operator on LXD with no real use as such but all seems to be working fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Models area of dashboard.
2. Click on model name other than "controller"
3. Boom!

**Expected behaviour**
After clicking on the model I'd expect to see something not unlike I see for the controller model...

![Screenshot from 2020-05-27 09-32-36](https://user-images.githubusercontent.com/4710/82996548-06eda000-9ffd-11ea-8b69-6de173d1b248.png)

**Desktop (please complete the following information):**
 - OS: Elementary 5.1
 - Browser Firefox 76.0.1

Of note, whenever I refresh the dashboard I have to log in again.

**Comment by hatched** [comment]
Thanks for filing this issue, I'll have to deploy this to see if I can reproduce locally because unfortunately that error message isn't very helpful :)

The issue about logging in after refresh is being tracked here: https://github.com/canonical-web-and-design/jaas-dashboard/issues/477 I'm going to try and prioritize this in the next month.

**Comment by hatched** [comment]
I believe I've resolved this issue in #520, once that lands I'll create a new release for Juju to see if it resolves it for you.

**Comment by hatched** [comment]
A new version has been released, 0.1.6 beta. 

To upgrade:
- `juju upgrade-dashboard && juju dashboard` 

If you wouldn't mind checking to see if this resolves the issue in viewing your model.

**Comment by ianmjones** [comment]
Thanks @hatched, but unfortunately same result on both Firefox 76 and Chromium 81.

![Screenshot from 2020-05-28 08-07-45](https://user-images.githubusercontent.com/4710/83110984-c99c1780-a0bb-11ea-9160-0a32daa2dbe1.png)

![Screenshot from 2020-05-28 08-16-39](https://user-images.githubusercontent.com/4710/83111002-d15bbc00-a0bb-11ea-9f93-accb1396cad0.png)

But the fix ups for layout are looking good...

![Screenshot from 2020-05-28 08-13-19](https://user-images.githubusercontent.com/4710/83111063-edf7f400-a0bb-11ea-8b56-a08723875bde.png)

**Comment by ianmjones** [comment]
Just to double check stuff, I added a new `gm-dev-pg` model and deployed `postgresql`, worked fine ...

![Screenshot from 2020-05-28 08-35-12](https://user-images.githubusercontent.com/4710/83113513-a8d5c100-a0bf-11ea-8143-416fcf129439.png)

Then I deployed that same `cockroachdb-operator` charm with 3 units to the model, link no longer worked.

After removing the 3 cockroachdb units, still didn't work, but once I removed the cockroachdb application from the model, I could get to the model again.

Then I stayed on that working model page with just postgresql, and deployed cockroachdb to see what would happen. Sure enough, within a few seconds, as soon as the machine was up, got the "Something has gone wrong..." error.

Once I removed the cockroachdb application again, as expected the page didn't magically fix itself, but as soon as I refreshed and logged in again the model was available for view.

I'm guessing this is related to either a problem with the `cockroachdb-operator` charm, but more likely, I suspect it's because the charm is not available on the store.

There's a 404 error message related to grabbing the icon.svg visible in my previous post's Chromium screenshot that I expect is relevant.

**Comment by hatched** [comment]
That was my thought as well, in testing I had resolved one 'local charm' issue which was why I thought it was resolved. I'll be working on this this afternoon and hopefully get a fix out today.

**Comment by hatched** [comment]
@ianmjones I believe I've now finally resolved this issue :-)

0.1.7 has been released and you can give it a try by running `juju upgrade-dashboard`. I'd be interested to know if this resolves this issue for you.

**Comment by ianmjones** [comment]
@hatched yup, works for me, thank you!
