### ISSUE TITLE
Model detail page, machine bit doesn't match design

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#518]
Current table, machine section:
![Screenshot 2020-05-27 at 14.53.13.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/9ed350b3-2817-4fd6-9a0c-b1e2ee0f4076)

Design:
![Screenshot 2020-05-27 at 14.54.09.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/4737c4c9-595a-4386-9c1a-e4e593d000ed)

A part from the machine performance charts that we know we can't have without a plugin, the Ubuntu series is not currently displayed on our table. This information is also present on juju status 2.8:
![Screenshot 2020-05-27 at 14.55.26.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/3b1e55dc-10ee-4d00-ba86-647592cc39ab)

**Comment by hatched** [comment]
We can't do the graphs but I can put the series beside the machine number and add the machine constraints data.

**Comment by clagom** [comment]
Wait on the constraint as I’m designing the UX, but we can proceed with the OS series please
