### ISSUE TITLE
Juju status CLI displays more information and data than the Dashboard model detail view

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#523]
Same model, Juju CLI output for `juju status`:
![Screenshot 2020-05-28 at 13.26.57.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/6c5ef7d9-04ca-4e50-85f1-a8e5b264026a)

Same model, how it appears on the Dashboard:
![Screenshot 2020-05-28 at 13.27.07.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/7f21dc0a-f912-4a88-a9f4-d31e9f82b6da)

In the UI we are missing some data that is present on the shell:
Scale, revision, charm, ports, series (we have an issue for series itself).

**Comment by hatched** [comment]
Please try again with the latest release `juju upgrade-dashboard && juju dashboard`
