### ISSUE TITLE
Error: Something has gone wrong. If this issue persists, please raise an issue on GitHub.

### ISSUE THREAD

**Issue by erik78se** [canonical-web-and-design/jaas-dashboard#524]
**Describe the bug**
The dashboard throws me an error as:

"Error: Something has gone wrong. If this issue persists, please raise an issue on GitHub."

**To Reproduce**
1. Go to 'https://jaas.ai/models"
2. Click on 'one of my models that lives in the aws'
3. . See error as above.

**Expected behavior**
I would like to know more on what acctually goes wrong except an error and nothing more.

**Screenshots**
<img width="549" alt="dashboard-1-jaas" src="https://user-images.githubusercontent.com/850603/83164697-d09f4600-a10c-11ea-8c35-619eab3754fa.png">
<img width="522" alt="jaas-gui-first-click" src="https://user-images.githubusercontent.com/850603/83164734-d85eea80-a10c-11ea-803b-99a90a91ede1.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version: 81.0.4044.138 (Officiell version) (32 bitar) (cohort: Stable)

**Comment by hatched** [comment]
Does this model contain any 'local' charms?

**Comment by erik78se** [comment]
Not sure... I was not even aware that it was there.

Den tors 28 maj 2020 18:44Jeff Pihach <notifications@github.com> skrev:

**Comment by hatched** [comment]
#515 is likely related here if it's a local charm. I'll keep this issue open until I've resolved the local charm issue in hopes that also resolves this.

**Comment by erik78se** [comment]
It would be good to get more details on what to report as part of a useful
bug report

Den tors 28 maj 2020 19:47Jeff Pihach <notifications@github.com> skrev:

**Comment by hatched** [comment]
I agree, it would certainly make debugging it a lot easier for me too 😆

**Comment by barrymcgee** [comment]
> It would be good to get more details on what to report as part of a useful
bug report

Thank you Erik, I've added an issue for this idea here: https://github.com/canonical-web-and-design/jaas-dashboard/issues/525

**Comment by hatched** [comment]
I'm hoping #528 will resolve this issue, once it's landed and a new release has been made to JAAS I'll update this issue for some additional testing.

**Comment by erik78se** [comment]
I will test more once I know what I'm waiting for?

New release of GUI or Juju?

Den fre 29 maj 2020 03:28Jeff Pihach <notifications@github.com> skrev:

**Comment by hatched** [comment]
@erik78se It looks like you ran into that issue on jaas.ai/models - that's now been updated to 0.1.7 which should contain a fix for this problem. If you wouldn't mind taking a look and letting me know.

**Comment by erik78se** [comment]
It seems to work I can confirm.

Den mån 1 juni 2020 17:10Jeff Pihach <notifications@github.com> skrev:

**Comment by hatched** [comment]
Great thanks!
