### ISSUE TITLE
Use default icon for local charms

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#527]
We're not currently able to display local charm icons, can we create and add a default icon?
<img width="1680" alt="Screen Shot 2020-05-28 at 7 17 32 PM" src="https://user-images.githubusercontent.com/532033/83211172-a86a1400-a119-11ea-869d-981867b4cab3.png">

Related: #438

**Comment by spencerbygraves** [comment]
@hatched https://assets.ubuntu.com/v1/7283ed9d-default-charm-icon.svg
