### ISSUE TITLE
Missing a breaking point for the responsive of the model detail page

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#546]
The topology is supposed to disappear when the page gets narrow, as per design.

- Wide default view (currently implemented, 1680px):
![Screenshot 2020-06-04 at 10.17.09.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/57bf6a37-5467-4358-bb62-8808d630f2aa)

- Narrow topology column (currently implemented, 1579px):
![Screenshot 2020-06-04 at 10.17.18.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/d813e4c4-1b8f-472c-b5f6-e63cbbf19461)

- Topology column disappear (missing breaking point, 1259px):
![Screenshot 2020-06-04 at 10.17.18.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/559d6d48-5c07-47d2-8938-6192fa565aca)

The other narrow views down to mobile are still valid.

**Comment by anthonydillon** [comment]
How does the user see the topology when split screen with a terminal? Is there a trigger to view it somewhere?

**Comment by clagom** [comment]
They go on mobile view

**Comment by clagom** [comment]
Or split the windows horizontally instead of vertical

**Comment by anthonydillon** [comment]
Huh? What do you mean by go on mobile view?

**Comment by clagom** [comment]
<img width="1680" alt="Screenshot 2020-06-04 at 15 29 56" src="https://user-images.githubusercontent.com/1953388/83769866-4a3cb400-a678-11ea-877b-339b92be2574.png">
<img width="1680" alt="Screenshot 2020-06-04 at 15 30 09" src="https://user-images.githubusercontent.com/1953388/83769874-4c9f0e00-a678-11ea-9e34-b0490318069d.png">

BTW, overall I don't think for this use case we need to reduce responsive break points right?

**Comment by hatched** [comment]
I'm -1 on removing the left column entirely without any ability for it to be made visible again. I agree that it's of lower importance than the data in the table however...

There was a design that had the Topology in the 'View' buttons in the top right. If we add that button back in there then I'd be ok hiding it depending on the width of the screen.

**Comment by clagom** [comment]
Ok, please add it back

**Comment by hatched** [comment]
So the actionable tasks here are:
- Add a "Topology" toggle to the View toggles in the top right.
  - Which is toggled 'on' by default
- At <insert pixels here> break point the toggle for "Topology" is toggled off.
- At <insert pixels here> break point the toggle for "Topology" is toggled back on for the mobile view.

@clagom can you add the two different values for the breakpoints between the brackets above.

**Comment by clagom** [comment]
Added issue and the existing design here:
https://github.com/canonical-web-and-design/jaas-dashboard/issues/547

**Comment by clagom** [comment]
Added values for breakpoints @hatched

**Comment by cristinadresch** [comment]
closing as its not relevant anymore with new designs
