### ISSUE TITLE
Pie charts are not rendered with 0 applications/units

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#555]
If your controller has no models or units then the pie charts on the controller page do not get rendered.

![Screen Shot 2020-06-15 at 3 49 37 PM](https://user-images.githubusercontent.com/532033/84710177-ef7d4500-af20-11ea-91ae-674bfa7f7bf7.png)

**Comment by barrymcgee** [comment]
@clagom What do you expect to see here when there is no data to generate a donut chart? Should the whole chart and legend be hidden?

**Comment by clagom** [comment]
I think we can leave it empty, but I would make it look disabled, not the same grey as running @spencerbygraves

**Comment by spencerbygraves** [comment]
@barrymcgee @clagom the current value for disabled in Vanilla is opacity .33
