### ISSUE TITLE
Adjust spacing and alignment of 'configuration' column

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#561]
- Swap the positions of the number count and the icon.
- This uses the new icon set.
- Align the three columns of the count to allow for 3 number spacing on each column
- Hover state is still being iterated on and can be done as a follow-up with the new machine view.

![Screen Shot 2020-06-16 at 9.52.33 AM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/a8e2d3ef-203c-48e9-8d48-81205488d8e7)

https://app.zeplin.io/project/5d2dfd8e5b67f14c5e1d2aef/screen/5ee8b159dfc05198ba40b2ad

**Comment by spencerbygraves** [comment]
@hatched I've added an [updated version to Zeplin](https://zpl.io/a7AZxxR).

**Comment by ziheliu214** [comment]
All proposed features are done, just need to link icons to relevant pages (another issue)
