### ISSUE TITLE
When not on jaas.ai, change links to be external

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#572]
All links to jaas.ai in the primary nav dropdown are external if the dashboard is launched from Juju. 

Should they all have external link icon or should the external link icon be removed from all?

<img width="271" alt="Screenshot 2020-06-18 at 12 06 05" src="https://user-images.githubusercontent.com/505570/85013280-3acf6780-b15c-11ea-92a6-d98f44b167e3.png">

**Comment by spencerbygraves** [comment]
I think that's a call for @clagom and @ziheliu214

**Comment by clagom** [comment]
I would say all external. Might be useful for users who are working locally to see that they point somewhere else.

**Comment by ziheliu214** [comment]
> I would say all external. Might be useful for users who are working locally to see that they point somewhere else.

All external +1
