### ISSUE TITLE
Upgrade to older version

### ISSUE THREAD

**Issue by Zouuup** [canonical-web-and-design/jaas-dashboard#578]
Hi! Thanks for the effort, but at this point, dashboard isn't really production-ready, and it is a bit weird that juju is now being preinstalled with it.

Quick question: how can I downgrade to gui 2.15?

**Comment by hatched** [comment]
Hi @Zouuup 

The short answer is that you can't. The long answer is that Juju 2.8 only ships with the new dashboard, you could run the old GUI by cloning the repo, running it in dev mode and pointing it at your controller if you still wanted to use it on 2.8; but it's no longer getting updates.

The dashboard is still very early in development and we're planning on adding a lot of new features however it is a shift in direction from the old GUI. More information: https://discourse.juju.is/t/jaas-dashboard-the-new-juju-gui/2978

I'd be interested to hear what features you'd like to see in the dashboard as it helps us prioritize the work.

**Comment by Zouuup** [comment]
Hi @hatched,

will make sure to join the discourse, and will do my best to provide feedback to improve this awesomeness!

But still, bro, we are depending on this software to deliver real-world, production infrastructures, it doesn't make sense to ditch old GUI while the new one is early in development...

**Comment by clagom** [comment]
Hi @Zouuup, would you be available to be contacted for a user interview? Would be really valuable for us and the product to understand how you used the old GUI and your requirements for the Dashboard. Once you are on Discourse we can exchange DMs.

**Comment by Zouuup** [comment]
@clagom Sure!
