### ISSUE TITLE
Erroneous console error appearing on page load

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#589]
<img width="1440" alt="Screenshot 2020-07-07 at 13 58 22" src="https://user-images.githubusercontent.com/505570/86785526-aa998980-c05a-11ea-991c-d8897c8036eb.png">

**Comment by hatched** [comment]
Thanks,

This is simply a log in the wrong place in the code and it can be ignored. The next release of the dashboard will resolve this.
