### ISSUE TITLE
Header on the Controller view isn't full width in mobile view.

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#604]
To reproduce go to `/controllers` and shrink the window as far as it'll go and you'll see this space. It disappears when switching to the regular widths.

![Screen Shot 2020-07-22 at 4 08 54 PM](https://user-images.githubusercontent.com/532033/88234421-20464d80-cc36-11ea-9c47-01f20a25c450.png)

**Comment by barrymcgee** [comment]
This issue no longer exists.
