### ISSUE TITLE
Register controller user/pass tick box should be dynamic

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#613]
@hatched It appears from this message that if both user and pass input fields have a value, this checkbox should disappear?

<img width="549" alt="Screenshot 2020-07-23 at 08 52 51" src="https://user-images.githubusercontent.com/505570/88263504-0b170080-ccc2-11ea-8114-3401a3fc779c.png">

**Comment by hatched** [comment]
That's a good idea.

@ziheliu214 can you take this into consideration when working on the UI/UX.
