### ISSUE TITLE
"Visit the controller" is a dead link

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#617]
<img width="564" alt="Screenshot 2020-07-23 at 09 08 31" src="https://user-images.githubusercontent.com/505570/88265441-6991ae00-ccc5-11ea-8c9a-c423d610a3f1.png">

**Comment by hatched** [comment]
It's a dynamic link that's generated based on what you've inputted in the controller api field.

If that field hasn't been populated then we should probably remove the link or update the text accordingly.
