### ISSUE TITLE
Upgrade to vanilla-framework 2.4.0

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#63]
There are some styling issues when applying this update that'll need some eyes on to resolve.

**Comment by clagom** [comment]
Can we estimate this? @barrymcgee @hatched thanks

**Comment by clagom** [comment]
I am not sure we can deliver this for this iteration, as small tasks is becoming bigger and bigger (I removed a few issue). Can we estimate this so that we can see if it's doable or needs to be planned next? Thanks CC @cristinadresch

**Comment by spencerbygraves** [comment]
@clagom, In stand up yesterday, @anthonydillon said to not update to 2.4.0 as it's broken, but wait for 2.4.1

**Comment by clagom** [comment]
Sounds good then we remove this from this iteration

**Comment by hatched** [comment]
We're now using 2.4.1
