### ISSUE TITLE
[Additional controller] Provide user feedback when adding additional controller

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/jaas-dashboard#640]
I suggest adding additional controllers to the additional list straight away and show a spinner until the data is loaded.

Further improvements would be:
- Display errors when adding additional controllers
- Provide actions to rectify the error or issue
- Allow the user to remove a controller from the list
- Provide the ability to remove all additional controllers (aid the logout discussion)
- Extended validation such as clashing local controller names

**Comment by hatched** [comment]
I've created or expanded the individual issues for all of the items in this. Thanks!
