### ISSUE TITLE
Leader information not shown in unit list

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#645]
When a unit is in HA and a leader has been elected we should indicate as such. 

I'd expect to see the leader status in the unit list but also in the unit details. @ziheliu214 can you add this to the unit list/details designs please.

related: https://discourse.juju.is/t/leadership-in-juju-operations-perspective/3406

**Comment by ziheliu214** [comment]
Its been noted and added to all latest UX designs.
