### ISSUE TITLE
The width of the panel covers the list on the left completely

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#683]
The width of the panel covers the list on the left completely, by design should leave (at least at max width) space to the left to select other apps/units/machines:
![Screenshot 2020-09-16 at 19.44.29.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/50bc64c6-6a89-4664-8d07-c84b6e91c7ac)

**Comment by hatched** [comment]
This will have to fall down at some point to support mobile and smaller screens. Do you have breakpoints and widths in mind already?

What happens (using the current image above) if I drag the window narrow, is that left edge of the panel fixed? Or can it move over until ultimately covering up everything (mobile view)?

**Comment by clagom** [comment]
Yes, at some point it has to happen and on mobile it can go full screen. It should come from Vanilla (when we use that layout)

**Comment by hatched** [comment]
We will need to know what those rules are before we can implement a fix to this unless you simply want the default to be narrower (right now it's `75vw`).

**Comment by hatched** [comment]
Estimating high because of unknown requirements.

**Comment by lyubomir-popov** [comment]
@hatched @clagom We'll [will add](https://github.com/canonical-web-and-design/vanilla-framework/issues/3282) out of the box responsive panels in vanilla, with potentially a choice of sizes, but in a case like this, taking the content in consideration would be better IMO. My thought process below.

Can we assume that:

- The panel makes sense as an overlay (and not a full separate view) as long as people can make out a meaningful part of the app's name (first column in the table under the panel)
- It's ok to hide columns in the panel's table responsively, to make room for more important content in the main area. (It currently happens by means of horizontal scroll)

Assuming the above are correct, then we could define:

- **A min-width for the main area:** Any less than that, we might as well hide the whole thing. Measuring content and margins that is 48+16+230+16+150+16 = 476px. (If any of these are in % or different values, we can do calc(...))
- **A min-width for the panel:** How many columns can we clip by the currently implemented responsive behaviour (horizontal scroll within the table), before loosing the context of the main view becomes less of a compromise than displaying panel content in a tiny width?

Adding these two up gives us a resolution at which the panel needs to move from right hand side sliding panel to bottom - up sliding panel or a full view (In other words, opt for one of the two behaviours specced out [here](https://app.zeplin.io/project/5ee74c8c07ded4b9e620e4f0/dashboard?seid=5f1abe1aac31a8444db34b27))

The panel also needs a max-width - I'd propose `min-content`. That means it will never take up more space than it needs to.

**Comment by clagom** [comment]
Thanks @lyubomir-popov
