### ISSUE TITLE
Panel with semi-transparent background 

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#685]
The background behind the panel seems to get semitransparent:
<img width="464" alt="Screenshot 2020-09-16 at 14 08 48" src="https://user-images.githubusercontent.com/1953388/93341579-30d60700-f826-11ea-9355-3eda976b28aa.png">

This panel is not a modal, so there shouldn't be any background when the panel is open

**Comment by barrymcgee** [comment]
@clagom This is to indicate that this area is disabled when the panel is open... clicking this area will close the panel and make this area interactive again. Is this wrong?

**Comment by clagom** [comment]
Yes, it's not how it's supposed to work by design. Disable the area would mean it's a modal panel, on the contrary we want to allow users to select other apps from the area without closing the panel necessary, first (in the future, this would even allow for multi-selection and grouped data in the panel). The fact that apps are not visible in the breakpoint is another separate matter. @barrymcgee
