### ISSUE TITLE
Keyline and spacing under 'Register a controller' seems off

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#689]
- What color should the keyline under the button be?
- What should the spacing under the button be?

<img width="707" alt="Screenshot 2020-09-21 at 14 12 15" src="https://user-images.githubusercontent.com/505570/93771092-f51bb280-fc14-11ea-863e-abb452202e6c.png">

**Comment by spencerbygraves** [comment]
@barrymcgee the colour should be #cccccc, same as models view and current Vanilla tables. We could try 8px for the spacing. Thanks.

**Comment by barrymcgee** [comment]
@spencerbygraves Should 'Model status across controllers' match the color and size of the table headers? #ccc is not in the Vanilla palette?

**Comment by spencerbygraves** [comment]
@barrymcgee 

>Should 'Model status across controllers' match the color and size of the table headers?

Yes please

>#ccc is not in the Vanilla palette?

On the Vanilla table it's specified as `rgba(0,0,0,0.2)`. Perhaps you could check with @lyubomir-popov please?

Thanks

**Comment by lyubomir-popov** [comment]
I don't think the muted heading was intended to use as a main page heading - hence the conflicting levels of hierarchy, with the table headers looking more prominent. We could add the table header style outside of tables if it is really needded. But here I wonder why not use an h4 for the "Model status across controllers"?

**Comment by spencerbygraves** [comment]
It's a table heading for the graphs, rather than a page heading.

**Comment by lyubomir-popov** [comment]
Oh ok. The color of <hr> (and similar borders) comes from this variable: 
`$colors--light-theme--border-default`
`$colors--light-theme--border-high-contrast` is for buttons, and 
`$colors--light-theme--border-low-contrast` is for more faint lines, like between the table rows or in the side navigation between groups of items

**Comment by barrymcgee** [comment]
@lyubomir-popov Thanks.. if that's a valid Vanilla colour for consumer use, I'd expect to see it listed here on the Colors page in docs? https://vanillaframework.io/docs/settings/color-settings

**Comment by lyubomir-popov** [comment]
@barrymcgee true, I've filed an [issue ](https://github.com/canonical-web-and-design/vanilla-framework/issues/3301) to document the theme colours.
