### ISSUE TITLE
Small design updates for the offline banner

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#694]
@barrymcgee until we have the finished notifications work, here are a few thoughts on improving what we have.

- [x] I've updated the padding to have .5rem top and bottom
- [x] Centred the text, currently it looks slightly off
- [x] I've added a dismiss icon on the right. @wgx mentioned in his demo that our users may find this useful
- [x] If we're true to the [Vanilla spec for inverted links](https://vanillaframework.io/docs/patterns/links#inverted), it should be 400 weight and underline on hover
- [x] I amended the text slightly on both

**Offline**

![image](https://user-images.githubusercontent.com/9105999/94254008-0bc84f00-ff1e-11ea-9217-649d937122f2.png)

**Online**

![image](https://user-images.githubusercontent.com/9105999/94254093-2c90a480-ff1e-11ea-81a7-d5ac6eee7cad.png)

Thanks

**Comment by cassiocassio** [comment]
- I'm sure there's good reasons to want to manage expectations when
connectivity drops, and returns, but this experience feels slightly needy.

- the strength of this big, important "your internet is down" warning
implies it's the only internet-aware bit of software on your machine. All
the other-things have presumably stopped updating, your mail, your
messages, your minimised tour de france feed... There's a wide variety of
"no internet" experiences - (I'm looking at you, Mattermost).

- I know that orange is our warning colour, these banners are simple, but
the dashboard is being a bit shouty here. "Calm-down jaas, I've just walked
away from the wifi for a second".

- If interactions become unavailable and data stale, we should consider an
offline state that communicates "not-live" and "don't click me now I'm a
dead button / link".

- I'm sure it's technically complex, but an app that loses connectivity,
and then regains it should, ideally, just spring back to life, and come
alive again, and bring the live data back. Presenting stale data and making
it the user's job to click to refresh seems like it's making this the
users' problem.

All of this is probably beyond this PR, I'm sure the challenge runs all the
way through the stack,  but gracefully managing the
online-offline-and-back-again experience seems like a worthy challenge.

**Comment by clagom** [comment]
I agree especially with the part where we ask users to refresh, it should do that automatically once it's back? E.g. display a "online now" and go. Maybe a follow up as might be late for this PR.

**Comment by wgx** [comment]
+1 to the usability concerns @cassiocassio raises.

**Comment by barrymcgee** [comment]
Yep.. pretty much all of the above was mentioned before this landed and the agreement was that this would land as-is and then we'd iterate. Thanks @spencerbygraves for the tweaks.
