### ISSUE TITLE
Example IP address in "Register a Controller" is invalid

### ISSUE THREAD

**Issue by phausman** [canonical-web-and-design/jaas-dashboard#697]
When I hit "Register a Controller", a form pops up. The description of the "Host" field contains invalid example IP address: "123.456.789.0:17070".

![image](https://user-images.githubusercontent.com/2110016/94374216-f6fcde80-010a-11eb-9521-4e1607329fee.png)

**Comment by hatched** [comment]
That was kind of intentional as it should be obvious not to copy and paste the example :) But this has been brought up a few times so we can change it.
