### ISSUE TITLE
The models section keeps erroring out. 

### ISSUE THREAD

**Issue by Phalen** [canonical-web-and-design/jaas-dashboard#717]
If I select a model with in about 2 min it will error out asking for a bug to be reported. it did not matter if it was the default or a project i was selecting. it would also 404 on models pages. 

**To Reproduce**
I installed following the instructions provided by ubuntu's cluster openstack directions.
after installing the juju server from step 5 I ran the command juju gui and after opening the console the error would happen regardless of how i opened the Models.  I would have to select one of the models to cause the crash. I had openstack, controller and default.  any of them would cause the error

**Expected behavior**
the status of the model would continuously be displayed.

ubuntu 20.04 lts was used for the server
ubuntu 18.04 lts as the deployment image.
the juju server was deployed to a vm on a known good kvm server.

**Comment by hatched** [comment]
Can you let us know what version of Juju you're using `juju version` and what version of the dashboard? You can find the version of the dashboard in the left column

![Screen Shot 2020-10-16 at 7 55 43 PM](https://user-images.githubusercontent.com/532033/96325923-a4b42c80-0fe9-11eb-880f-92b28e043687.png)

**Comment by hatched** [comment]
I'm going to close this for now, if you continue to have an issue feel free to respond and it can be re-opened.
