### ISSUE TITLE
Page titles should reflect current template view

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#744]
All pages in the dashboard currently have the same page title;

<img width="238" alt="Screenshot 2020-11-11 at 11 42 31" src="https://user-images.githubusercontent.com/505570/98807763-0d3cd080-2413-11eb-9483-94752cf01f52.png">

The page title should change to reflect each different template view.

**Comment by huwshimi** [comment]
In MAAS we use a hook to change the window title:

https://github.com/canonical-web-and-design/maas-ui/blob/master/ui/src/app/base/hooks.js#L116

**Comment by hatched** [comment]
Thanks @huwshimi
