### ISSUE TITLE
"Dashboard is now online" shown with small vertical height list

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#747]
To reproduce...

In Firefox
shrink the vertical height of your browser so it only shows 7 or so models then refresh
once they have loaded, scroll down, you'll see a ton of white space and at the top of the page...

![Screen Shot 2020-11-16 at 4 49 36 PM](https://user-images.githubusercontent.com/532033/99317482-bfb5ce80-282b-11eb-9100-80b7f0410835.png)

**Comment by barrymcgee** [comment]
There are two separate issues here;

1 - the online/offline banner is showing it's content despite being inactive
2 - there seems to be a application layout bug in Vanilla which is adding that large bottom spacing in Firefox

**Comment by barrymcgee** [comment]
The first issue should be addressed by the PR above.

The second issue should be addressed by https://github.com/canonical-web-and-design/vanilla-framework/pull/3397
