### ISSUE TITLE
Icons in the topology are rendered more and more incorrectly on every render

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#762]
Original: https://github.com/canonical-web-and-design/jaas-dashboard/pull/754#issuecomment-731558159

- When filtering the model details tables from status, units, machines, etc the topology rerenders incorrectly
![Peek 2020-11-21 10-11](https://user-images.githubusercontent.com/1413534/99874707-e7b58100-2be1-11eb-9e30-f998f21afb51.gif)

https://github.com/canonical-web-and-design/jaas-dashboard/pull/754/files#diff-a99d1c4c6d7e00032690d4312352762fe343b68ac6b0391eb8c541a7b1dc7194R115

**Comment by spencerbygraves** [comment]
@hatched hidden zoom feature? 😉

**Comment by cristinadresch** [comment]
@hatched we assigned this to you this iteration, if you could also estimate it please

**Comment by anthonydillon** [comment]
Confirmed its fixed via https://github.com/canonical-web-and-design/jaas-dashboard/pull/754/commits/23427c39477c64cca4c8a5a7b730cd29e3bffcbb
