### ISSUE TITLE
Inconsistent spacing in status count

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#773]
The spacing between `6 applications` and `5 waiting` is smaller than the space between `5 waiting` and `1 unknown`.

The gap between `5 waiting` and `1 unknown` should be the same as the gap between `6 applications` and `5 waiting` .

![Screen Shot 2020-11-27 at 9 49 04 AM](https://user-images.githubusercontent.com/532033/100466026-debb2880-3095-11eb-83e5-584cf21c5ae1.png)

**Comment by long-chung** [comment]
The spacing is correct. 
Space between "6 applications: 5 waiting" = 8px (0.5 rem)
Space between each status = 16px (1rem)
