### ISSUE TITLE
Scrollbar across the whole page on top of the user icon

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#775]
The scrollbar appears across the whole page on top of the user icon.
![Screenshot 2020-11-30 at 12.42.03.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/52766b70-73a0-46b5-8649-18ebe07246c7)

**Comment by barrymcgee** [comment]
@clagom What is the screen resolution and browser you are using to replicate this please?

**Comment by clagom** [comment]
I saw this on @wgx's work about Notifications. Will can you please provide more info thanks.

**Comment by wgx** [comment]
@barrymcgee just played around and couldn't replicate exactly, closest I got was this:

![image](https://user-images.githubusercontent.com/930099/101363566-77715580-3899-11eb-921c-d4cce144a464.png)

**Comment by wgx** [comment]
User Agent | FIREFOX              Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0,gzip(gfe)
Language | en-GB,en;q=0.5
Plugins |  
Cookies | Enabled
Screen Resolution | 1920 X 1080       (1920 X 1057)

**Comment by barrymcgee** [comment]
Closing this as I cannot currently replicate - I think it was a regression that was resolved elsewhere.
