### ISSUE TITLE
TypeError: Cannot read property 'logout' of undefined

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#790]
https://sentry.is.canonical.com/canonical/juju-dashboard/issues/13437/?referrer=github_plugin

```
TypeError: Cannot read property 'logout' of undefined
  at None (../../api/client.ts:162:12)
```

**Comment by barrymcgee** [comment]
I'm getting this _alot_

**Comment by barrymcgee** [comment]
Fixed in this repo by https://github.com/canonical-web-and-design/jaas-dashboard/pull/819
