### ISSUE TITLE
Unable to log into terminal

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#80]
<img width="1407" alt="Screenshot 2019-10-14 at 13 19 42" src="https://user-images.githubusercontent.com/505570/66750817-5ecc0200-ee85-11e9-8c67-17bbad0f63a7.png">

The error message: 

```
Close and re-open the terminal window to reconnect.
```

...is confusing as we don't provide a way for the user to terminate/restart the terminal.

**Comment by hatched** [comment]
That message is from the server so we don't have easy control over it. Were you able to refresh and have it working again?

**Comment by barrymcgee** [comment]
> That message is from the server so we don't have easy control over it. 

I know this but the user does not. 

No, this error persists despite flushing localstorage, caches, logging-in again etc

**Comment by hatched** [comment]
I'm able to reproduce the original issue now - I'll address the fix shortly.
