### ISSUE TITLE
Can not visit Controllers while trying to register a localhost

### ISSUE THREAD

**Issue by hwpplayer1** [canonical-web-and-design/jaas-dashboard#800]
**Describe the bug**
Can not visit Controllers while trying to register a localhost
**To Reproduce**
1. Go to 'I pass my credentials and login to dashboard '
2. Click on 'Controllers'
3. Scroll down to '...'
Error: Something has gone wrong. If this issue persists, please raise an issue on GitHub.

**Expected behavior**
Few minutes ago i was able to see Controller section
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04 Focal]
 - Browser [Microsoft Edge Chromium and the Chromium]
 - Version [Version 88.0.705.9 (Official build) dev (64-bit) for Microsoft Edge Chromium and Version 87.0.4280.88 (Official Build) snap (64-bit) for the Chromium]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hwpplayer1** [comment]
As you can understand i am trying to learn and find new ways like actions with command line or GUI or Web Interface.

juju dashboard is a working solution which i run on the terminal

I'll give feedback in a few minutes

**Comment by hwpplayer1** [comment]
I cleared the cookies and the old dashboard is working. Thanks.

**Comment by hatched** [comment]
Sorry you ran into that issue but I'm glad it's working out for you. Let us know if you run into any further issues.
