### ISSUE TITLE
Regression on the side navigation when collapsed, shows more content than supposed to

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#814]
To replicate just resize the window
![Screenshot 2021-01-07 at 15.07.57.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/ecfba804-f231-4007-b0ed-4b41d73dfdf4)

**Comment by anthonydillon** [comment]
You need to set `$application-layout--side-nav-width-collapsed: 3rem;` locally
