### ISSUE TITLE
Registered controller table appears even if empty

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#857]
<img width="1323" alt="Screenshot 2021-02-03 at 14 21 14" src="https://user-images.githubusercontent.com/505570/106759887-27113c80-662b-11eb-9aa8-004607e9eb8d.png">

**Comment by hatched** [comment]
This was intentional as it was from an era when we displayed empty tables. I don't feel strongly about it either way :)

**Comment by clagom** [comment]
It should at least say "no controllers" as in the models tables, otherwise seems a loading stuck state

**Comment by hatched** [comment]
As we don't render empty tables anywhere else any longer, for consistency sake lets only show it if `registered controllers > 0` :) (which I'm guessing is where @barrymcgee was heading with this issue)
