### ISSUE TITLE
Update new user message link

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#865]
The link in the image below is no longer correct and needs to be updated to the `charmhub.io` link.

![Screen Shot 2021-02-08 at 11.54.24 AM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/cade64ee-cebc-487f-8c1f-a2534703b78f)

**Comment by barrymcgee** [comment]
@hatched What charmhub.io link?

**Comment by anthonydillon** [comment]
The [discourse link](https://github.com/canonical-web-and-design/jaas-dashboard/blob/c75d9c9091787a42b97eee02929f8c860bd83e25/src/components/Layout/Layout.js#L106) should be updated to charmhub.io.

**Comment by barrymcgee** [comment]
The new link is: https://discourse.charmhub.io/t/jaas-dashboard-the-new-juju-gui/2978
