### ISSUE TITLE
WebCLI shows user undefined when user tries to submit command

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#871]
- Toggle on WebCLI via config
- Go to model details page
- Click into WebCLI
- Type `status` and hit enter
- See:

<img width="1345" alt="Screenshot 2021-02-09 at 11 39 39" src="https://user-images.githubusercontent.com/505570/107358712-9d022180-6acb-11eb-97eb-d2721293263a.png">

**Comment by hatched** [comment]
This is because it's trying to use a macaroon to log in but currently the UI only supports u/p login for the wcli.

Up until recently we didn't have a setup capable of testing the macaroon login flow for the wcli. I'll pick this up this week.
