### ISSUE TITLE
WebCLI covers the bottom of the panel

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#875]
The WebCLI is covering the footer of the panel.

![Screen Shot 2021-02-09 at 1.34.11 PM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/728dcbf9-d683-4d52-a095-9004ab4ae8a5)

**Comment by barrymcgee** [comment]
Closed by https://github.com/canonical-web-and-design/jaas-dashboard/pull/876
