### ISSUE TITLE
Clicking the unit in the machine view doesn't do anything

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#917]
![Screen Shot 2021-03-10 at 9.42.35 AM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/cbfc46d5-9308-429e-874b-7d5ce01bc074)

Clicking that unit row should take you to the unit details page.

**Comment by anthonydillon** [comment]
Did this ever work?

**Comment by hatched** [comment]
I am pretty sure it did before the new layout
