### ISSUE TITLE
Waiting for 3 kube-system pods to start

### ISSUE THREAD

**Issue by pratapsahu1980** [canonical-web-and-design/jaas-dashboard#931]
Charmed-Kubernetes
---------------------------------------------------------------------------------

kubernetes-master/0       waiting   idle       5        10.189.203.111  6443/tcp        Waiting for 3 kube-system pods to start
  containerd/1            active    idle                10.189.203.111                  Container runtime available
  flannel/1               active    idle                10.189.203.111                  Flannel subnet 10.1.66.1/24
kubernetes-master/1*      waiting   idle       6
        10.189.203.148  6443/tcp        Waiting for 3 kube-system pods to start
  containerd/0*           active    idle                10.189.203.148                  Container runtime available
  flannel/0*              active    idle                10.189.203.148                  Flannel subnet 10.1.7.1/24

KUBERBETES-MASTER IS KEEP WAITING. 
abc@server:~$ kubectl get pods -A
NAMESPACE                         NAME                                                      READY   STATUS    RESTARTS   AGE
ingress-nginx-kubernetes-worker   default-http-backend-kubernetes-worker-6494cbc7fd-mgcsw   0/1     Pending   0          6h47m
ingress-nginx-kubernetes-worker   nginx-ingress-controller-kubernetes-worker-4n8hk          0/1     Pending   0          6h24m
kube-system                       coredns-7bb4d77796-nxlbj                                  0/1     Pending   0          6h59m
kube-system                       kube-state-metrics-7f55b9fcd7-b78qw                       0/1     Pending   0          6h59m
kube-system                       metrics-server-v0.3.6-7d66499544-9xrqj                    0/2     Pending   0          6h59m
kubernetes-dashboard              dashboard-metrics-scraper-74757fb5b7-xmv7h                0/1     Pending   0          6h59m
kubernetes-dashboard              kubernetes-dashboard-64f87676d4-lrcdm                     0/1     Pending   0          6h59m

CAN ANYONE HELP ?

**Comment by hatched** [comment]
Hi @pratapsahu1980 this is the repository for the Juju Dashboard itself. If you're looking for help with a charm or Juju you'd be best to try https://discourse.charmhub.io/ or the charm authors directly.
