### ISSUE TITLE
Some apps cause a form error

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/jaas-dashboard#947]
**Describe the bug**
Some apps (for example cs:~nrpe-charmers/nrpe-53) cause a form error when visiting the application view.

**To Reproduce**
1. add-model test
2. juju deploy cs:~nrpe-charmers/nrpe-53 --series focal
3. Go to http://localhost:3001/models/{username}@external/test/app/nrpe
4. See the error

**Expected behavior**
Should display the app view without an error

**Additional context**
Error:
```
TypeError: can't convert null to object
onFormChange
src/pages/EntityDetails/App/App.tsx:143

  140 | 
  141 | const onFormChange = (formData: FormData) => {
  142 |   if (!setFieldsValues.current) return;
> 143 |   const unitList = Object.keys(app.units);
      | ^  144 | 
  145 |   // Handle the selectAll checkbox interactions.
  146 |   if (selectAll.current && !formData.selectAll) {

FormikFormData/<
src/components/FormikFormData/FormikFormData.tsx:24

  21 | }, [onSetup, setFieldValue]);
  22 | 
  23 | useEffect(() => {
> 24 |   onFormChange(values);
     | ^  25 | }, [onFormChange, values]);
  26 | 
  27 | return <Form>{children}</Form>;
```

**Comment by hatched** [comment]
This is because subordinates on their own do not have units. Will have to code defensively around this eventuality.
