### ISSUE TITLE
The button " Give feedback" does not work...

### ISSUE THREAD

**Issue by moula** [canonical-web-and-design/jaas-dashboard#963]
1- The button "Give feedback "does not work
2- Another question :
Why the version on a bare-metal deployment still 0.3 beta while on Jaas is version 0.5? 
the juju upgrade-dashboard command does nothing new.
Thank's. 
![Screenshot_2021-04-16 Juju Dashboard(4)](https://user-images.githubusercontent.com/1804815/115046966-59b39d00-9ed8-11eb-9043-e563e4347fdd.png)

**Comment by hatched** [comment]
Thanks for bringing this up.
We'll look into this.
A new version of the dashboard will be coming with Juju 2.9.

**Comment by moula** [comment]
Thank's 
I'm already on version 2.9 :-) 
![Screenshot_2021-04-16 Terminal - maas1(4)](https://user-images.githubusercontent.com/1804815/115054513-92577480-9ee0-11eb-8fa4-22a8517f1cb8.png)

**Comment by hatched** [comment]
HAH ok you caught me, when 2.9 gets "released" ;)

We're actually hoping to get a beta release out for 2.9 next week 🤞 I'll reply here when it goes out.

**Comment by moula** [comment]
Hello, 
Sorry Jeff, I'm on juju 2.9.1 already but still juju-dashboard 3.0 !!!
No worries I will wait for you, thank you for your fabulous work.
![Screenshot_2021-04-28 Terminal - maas1](https://user-images.githubusercontent.com/1804815/116449821-d9d3ee00-a85a-11eb-8256-a0eedd3e7b6b.png)

**Comment by hatched** [comment]
Yes I apologize for the delay. With the 2.9 release we found an issue in the dashboard and had to roll it back. I'm working on a resolution now.

**Comment by hatched** [comment]
@moula Juju 2.9 (and 2.8.x) are now both deploying the lastest dashboard 0.6.2.

Thanks for your patience!
