### ISSUE TITLE
Bug on mouse over the sidebar

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#98]
Under the JAAS logo (and before 'model') there is a mouse over status for an item that shouldn't be there:
![Screenshot 2019-10-21 at 17.02.32.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/e399ed98-1041-421c-82bb-ab04ccf6bd6c)

**Comment by hatched** [comment]
I'm not able to reproduce, can you make sure you're on the most current code and then do a fresh build?

**Comment by clagom** [comment]
It's on the last build from master, locally

**Comment by clagom** [comment]
A video: https://drive.google.com/open?id=1bwEy-bCFqFJSksClU6FuywAGFDzRr10F @barrymcgee @hatched
