### ISSUE TITLE
Trim web cli commands before submitting

### ISSUE THREAD

**Issue by moula** [canonical-web-and-design/jaas-dashboard#990]
Hi, 
When i enter the command : juju status on my shell, it works
x-special/nautilus-clipboard
![Capture d’écran du 2021-05-03 11-32-44](https://user-images.githubusercontent.com/1804815/116861917-32f9a400-ac04-11eb-87aa-9b9b91c03abd.png)

But when i try directly on juju-dashboard, i have : 
Message : shell Nothing matched specified filter.
![Capture d’écran du 2021-05-03 11-33-12](https://user-images.githubusercontent.com/1804815/116861944-40169300-ac04-11eb-91e6-9943d0f883b8.png)

**Comment by hatched** [comment]
I'm not able to reproduce this, did you just submit `status`? Is it possible you had an extra space at the end?

**Comment by moula** [comment]
Bonjour Jeff, 
Yes The problem, it's an extra space at the end. while juju status on the shell with space or not at the end it works.
![Capture d’écran du 2021-05-03 15-52-32](https://user-images.githubusercontent.com/1804815/116885376-1bccad80-ac28-11eb-96c5-240063698342.png)
![Capture d’écran du 2021-05-03 15-52-32](https://user-images.githubusercontent.com/1804815/116885395-21c28e80-ac28-11eb-9925-4384fb8719ba.png)

Thank's

**Comment by hatched** [comment]
Thanks! I'll add a trim to the command before it's submitted.
